IncludeScript("fatcat_library")
IncludeScript("chaosmvm/text-speech")
IncludeScript("chaosmvm/text-mission")
IncludeScript("chaosmvm/gameplay-applications")
IncludeScript("chaosmvm/weapons-abilities")
IncludeScript("chaosmvm/flame-sentry")
IncludeScript("chaosmvm/longbow-sentry")
IncludeScript("chaosmvm/item-helper")
IncludeScript("chaosmvm/translations")
//IncludeScript("chaosmvm/responses")

if ("__potato" in getroottable())
  ::__potato.GasNerf.Disable()

SetCvar("tf_use_fixed_weaponspreads", 0, false)
SetCvar("tf_forced_holiday", 2, false)
SetCvar("tf_mvm_respec_enabled", 0, false)
SetCvar("tf_parachute_deploy_toggle_allowed", 1, false)
SetCvar("tf_parachute_maxspeed_z", -63, false)
SetCvar("tf_parachute_maxspeed_xy", 600, false)
SetCvar("tf_grapplinghook_move_speed", 1200, false)
SetCvar("tf_rocketpack_toggle_duration", 0.5, false)
SetCvar("tf_rocketpack_launch_delay", 0.01, false)
SetCvar("tf_rocketpack_cost", 10), false
SetCvar("tf_rocketpack_refire_delay", 0.01, false)
SetCvar("tf_halloween_kart_boost_duration", 2), false
SetCvar("tf_halloween_kart_boost_recharge", 4, false)
SetCvar("tf_halloween_kart_normal_speed", 1000, false)
SetCvar("tf_halloween_kart_dash_speed", 1500, false)
SetCvar("tf_halloween_kart_fast_turn_accel_speed", 800, false)
SetCvar("tf_halloween_kart_fast_turn_speed", 120, false)
SetCvar("tf_halloween_kart_normal_accel", 2, false)
SetCvar("tf_halloween_kart_normal_accel", 250, false)
SetCvar("tf_halloween_kart_return_turn_accell", 600, false)
SetCvar("tf_halloween_kart_reverse_speed", -100, false)
SetCvar("tf_halloween_kart_reverse_turn_speed", -100, false)
SetCvar("tf_halloween_kart_slow_turn_accel_speed", 400, false)
SetCvar("tf_halloween_kart_slow_turn_speed", 120, false)
SetCvar("tf_halloween_kart_slowmoving_accel", 250, false)
SetCvar("tf_halloween_kart_stationary_turn_speed", 120, false)
SetCvar("tf_halloween_kart_slow_turn_accel_speed", 400, false)
SetCvar("sig_attr_speed_health_ammo_recalculate", 0, false)
SetCvar("sig_attr_display", 0, false)
